"use client"
import Image from 'next/image'
import LandingPage from '../components/LandingPage'
import Head from 'next/head'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Qr - Code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <LandingPage/>
    </div>
  )
}
